### ISSUE TITLE
All tables that have an audit table should correctly record changes.

### ISSUE THREAD

**Issue by comraderat** [gochan-org/gochan#31]

**Comment by erincerys** [comment]
I could help out with this! I've implemented such functionality using triggers in MySQL and Postgres.

The one gotcha is on record deletions, when you want to record an ID not already defined, such as the moderator who performed the deletion through the app. Unfortunately, I don't know any go, so I wouldn't be able to do that, if it's a detail you'd want included.

Does this issue include defining and creating the audit tables in the `initdb_*.sql` files? I don't see them there already.

**Comment by Eggbertx** [comment]
I definitely appreciate the help. @comraderat did all of the DB refactoring but unfortunately he had to drop out because of IRL concerns. Even if you're not familiar with Go, I'm sure I can integrate any SQL contributions you make.

For things like record deletion, if it's something like a staff member that no longer exists when the record is deleted, it will just be assumed that the staff member was removed.

There are a few auditing tables, though right now it's just DBPREFIXip_ban_audit, DBPREFIXip_ban_appeals_audit, and DBPREFIXreports_audit, and right now only DBPREFIXip_ban_appeals_audit is used in the code, in  /pkg/gcsql/queries.go in AddBanAppeal:

```Go
const sql1 = `
/*copy old to audit*/
INSERT INTO DBPREFIXip_ban_appeals_audit (appeal_id, staff_id, appeal_text, staff_response, is_denied)
SELECT id, staff_id, appeal_text, staff_response, is_denied
FROM DBPREFIXip_ban_appeals
WHERE DBPREFIXip_ban_appeals.ip_ban_id = ?`
const sql2 = `
/*update old values to new values*/
UPDATE DBPREFIXip_ban_appeals SET appeal_text = ? WHERE ip_ban_id = ?
`
```

If you're uncomfortable with using Go directly for SQL contributions though, you can just post them in this issue and I can just @ you in the commit message to give you credit.

**Comment by Eggbertx** [comment]
This issue is still in progress
